language: node_js
node_js:
  - 14.1.0
script:
  - npm run travis
after_success:
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
